language: android
# jdk:
#   - openjdk7
#   - oraclejdk7
#   - oraclejdk8
env:
  global:
    - TERM=dumb
    - ANDROID_ABI=armeabi-v7a
    - BUILD_TOOLS=build-tools-21.1.1,android-21
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_SDKS=$BUILD_TOOLS,sys-img-armeabi-v7a-android-tv-21  ANDROID_ABI=android-tv/armeabi-v7a
    - ANDROID_TARGET=android-21  ANDROID_SDKS=$BUILD_TOOLS,sys-img-armeabi-v7a-${ANDROID_TARGET}
    - ANDROID_TARGET=android-20  ANDROID_SDKS=$BUILD_TOOLS,sys-img-armeabi-v7a-android-wear-20  ANDROID_ABI=android-wear/armeabi-v7a
    - ANDROID_TARGET=android-19  ANDROID_SDKS=$BUILD_TOOLS
    - ANDROID_TARGET=android-18  ANDROID_SDKS=$BUILD_TOOLS
    - ANDROID_TARGET=android-17  ANDROID_SDKS=$BUILD_TOOLS
    - ANDROID_TARGET=android-16  ANDROID_SDKS=$BUILD_TOOLS
    #- ANDROID_TARGET=android-14  ANDROID_SDKS=$BUILD_TOOLS,${ANDROID_TARGET},sys-img-armeabi-v7a-${ANDROID_TARGET}
    #- ANDROID_TARGET=android-10  ANDROID_SDKS=$BUILD_TOOLS,sys-img-x86-${ANDROID_TARGET}  ANDROID_ABI=armeabi
    #- ANDROID_TARGET=android-8   ANDROID_SDKS=$BUILD_TOOLS,${ANDROID_TARGET}  ANDROID_ABI=armeabi

android:
  components:
    - $ANDROID_SDKS
    #- tools  # new version abailable, Failed to rename directory
    #- platform-tools  # pre-installed components, new version abailable, Failed to rename directory
    #- build-tools-21.1.1  # build-tools-20.0.0 is pre-installed, Install OK
    #- android-21  # Install OK
    #- android-19  # pre-installed components
    #- android-18  # pre-installed components
    #- sys-img-armeabi-v7a-$ANDROID_TARGET  # Instal OK
    #- sys-img-armeabi-v7a-android-19  # pre-installed components
    #- sys-img-x86-android-19  # pre-installed components, Could not find com.android.support:support-v4:21.0.0
    #- sys-img-armeabi-v7a-android-18  # pre-installed components
    #- extra-android-m2repository  # pre-installed components, new version abailable, Failed to rename directory
    #- extra-android-support  # pre-installed components, new version abailable, Failed to rename directory
    #- extra-intel-Hardware_Accelerated_Execution_Manager

before_install:
  - ./gradlew -v
  - uname -a
  - env | col | sort
  - android list targets | grep "id:"
  - android list sdk --no-ui --extended | grep "id:"
  - android list sdk --no-ui --extended --all | grep "id:"

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - ./gradlew build
  - ./gradlew connectedAndroidTest
  #- ./gradlew --full-stacktrace -q build
  #- ./gradlew --full-stacktrace build
  #- ./gradlew connectedAndroidTest --info

after_script:
  - cat /home/travis/build/ay65535/AndroidLoggerClient/build/outputs/reports/androidTests/connected/index.html
  - cat /home/travis/build/ay65535/AndroidLoggerClient/build/outputs/reports/androidTests/connected/css/base-style.css
  - cat /home/travis/build/ay65535/AndroidLoggerClient/build/outputs/reports/androidTests/connected/css/style.css
  - cat /home/travis/build/ay65535/AndroidLoggerClient/build/outputs/reports/androidTests/connected/js/report.js
  - cat /home/travis/build/ay65535/AndroidLoggerClient/build/outputs/reports/androidTests/connected/com.android.builder.testing.ConnectedDevice.html
  - cat /home/travis/build/ay65535/AndroidLoggerClient/build/outputs/reports/androidTests/connected/com.android.builder.testing.html


